#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

STDIN=$(cat)
APP="$1"
STORAGE_OPTIONS_FILE="STORAGE_OPTIONS"
STORAGE_OPTIONS_FILE_PATH="$DOKKU_ROOT/$APP/$STORAGE_OPTIONS_FILE"

output=""
if [[ -f "$STORAGE_OPTIONS_FILE_PATH" ]]; then
  DONE=false
  until $DONE; do
    read line || DONE=true

    [[ ! -n "$line" ]] && continue

    case "$line" in
      \#*)
        continue
        ;;
      *)
        output="$output -v $line"
        ;;
    esac
  done < $STORAGE_OPTIONS_FILE_PATH
fi

echo "$STDIN$output"
